#!/bin/sh

# firewall          Firewall
#
# chkconfig: 2345 55 25
# description: Firewall
#
# processname: firewall

### BEGIN INIT INFO
# Provides: firewall
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Firewall
# Description:       Custom Firewall.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

IPTABLES="/usr/bin/env iptables"

case "$1" in
        start|restart|reload)
                $IPTABLES -t nat -Z
                $IPTABLES -t nat -F
                $IPTABLES -t nat -X
                $IPTABLES -t mangle -Z
                $IPTABLES -t mangle -F
                $IPTABLES -t mangle -X
                $IPTABLES -Z
                $IPTABLES -F
                $IPTABLES -X
                $IPTABLES -P INPUT DROP
                $IPTABLES -P OUTPUT ACCEPT
                $IPTABLES -P FORWARD DROP
                $IPTABLES -A INPUT -i lo -j ACCEPT
                $IPTABLES -A INPUT -i eth0 -p tcp ! --syn -m state --state NEW -j DROP
                $IPTABLES -A INPUT -i eth0 -f -j DROP
                $IPTABLES -A INPUT -i eth0 -p tcp --tcp-flags ALL FIN,URG,PSH -j DROP
                $IPTABLES -A INPUT -i eth0 -p tcp --tcp-flags ALL ALL -j DROP
                $IPTABLES -A INPUT -i eth0 -p tcp --tcp-flags ALL NONE -m limit --limit 5/m --limit-burst 7 -j LOG --log-prefix "NULL Packets"
                $IPTABLES -A INPUT -i eth0 -p tcp --tcp-flags ALL NONE -j DROP
                $IPTABLES -A INPUT -i eth0 -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
                $IPTABLES -A INPUT -i eth0 -p tcp --tcp-flags SYN,FIN SYN,FIN -m limit --limit 5/m --limit-burst 7 -j LOG --log-prefix "XMAS Packets"
                $IPTABLES -A INPUT -i eth0 -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
                $IPTABLES -A INPUT -i eth0 -p tcp --tcp-flags FIN,ACK FIN -m limit --limit 5/m --limit-burst 7 -j LOG --log-prefix "Fin Packets Scan"
                $IPTABLES -A INPUT -i eth0 -p tcp --tcp-flags FIN,ACK FIN -j DROP
                $IPTABLES -A INPUT -i eth0 -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP
                $IPTABLES -A INPUT -i eth0 -m pkttype --pkt-type broadcast -j DROP
                $IPTABLES -A INPUT -i eth0 -m pkttype --pkt-type multicast -j DROP
                $IPTABLES -A INPUT -i eth0 -m state --state INVALID -j DROP
                $IPTABLES -A INPUT -i eth0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
                $IPTABLES -A INPUT -i eth0 -s %%YOUR_IP_HERE%% -p tcp --dport 80 -j ACCEPT
                $IPTABLES -A INPUT -i eth0 -s %%YOUR_IP_HERE%% -p tcp --dport 22 -j ACCEPT
                $IPTABLES -A INPUT -i eth0 -s %%YOUR_IP_HERE%% -p tcp --dport 443 -j ACCEPT
                $IPTABLES -A INPUT -i eth0 -s %%YOUR_IP_HERE%% -p tcp --dport 3128 -j ACCEPT
                $IPTABLES -A INPUT -i eth0 -s %%YOUR_IP_HERE%% -p tcp --dport 3129 -j ACCEPT
                $IPTABLES -A INPUT -i eth0 -s %%YOUR_IP_HERE%% -p udp --dport 53 -j ACCEPT
        		$IPTABLES -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3128
        		$IPTABLES -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 3129
                ;;
        stop)
                $IPTABLES -P INPUT ACCEPT
                $IPTABLES -P OUTPUT ACCEPT
                $IPTABLES -P FORWARD DROP
                $IPTABLES -F INPUT
                $IPTABLES -F FORWARD
                $IPTABLES -F OUTPUT
                ;;
        *)
                echo "Unknown Command"
                exit 1
                ;;
esac

